/*****************************************************************************
   can_753__0002.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon May 16 16:32:25 2022
 *****************************************************************************/

#ifndef __CAN_753__0002_H
#define __CAN_753__0002_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_753__0002(void);
extern void post_start_CAN_753__0002(void);

/* Receive CAN object declarations */
extern uint8_T can_get_290__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_289__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_78__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_78__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_78__0002(uint32_T period);
extern void can_send_79__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_79__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_79__0002(uint32_T period);
extern void can_send_76__0005(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_76__0005(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_76__0005(uint32_T period);
extern void can_send_77__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_77__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_77__0002(uint32_T period);
extern void can_send_121__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_121__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_121__0002(uint32_T period);
extern void can_send_258__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_258__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_258__0002(uint32_T period);
extern void can_send_259__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_259__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_259__0002(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_uds_send(uint32_T period);

#endif
