/*****************************************************************************
   lin_675__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 10 15:44:35 2023
 *****************************************************************************/

/*   LIN Bus: LIN2 */
/*  Resource: LIN2 */
#ifndef _LIN_675__0001_H
#define _LIN_675__0001_H
#endif
