/*****************************************************************************
   can_2067__0005.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 16:05:33 2023
 *****************************************************************************/

#ifndef __CAN_2067__0005_H
#define __CAN_2067__0005_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_2067__0005(void);
extern void post_start_CAN_2067__0005(void);

/* Receive CAN object declarations */

/* Transmit CAN object declarations */
#endif
