/*****************************************************************************
   lin_2068__0005.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 16:05:33 2023
 *****************************************************************************/

/*   LIN Bus: LIN2 */
/*  Resource: LIN2 */
#ifndef _LIN_2068__0005_H
#define _LIN_2068__0005_H
#endif
