/*****************************************************************************
   Timer_BGND_9AY_V.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Apr 12 17:38:25 2023
 *****************************************************************************/

#include "EB_Charging_Program_Feb.h"
#include "EB_Charging_Program_Feb_private.h"

void Timer_BGND_9AY_V(void)
{
  /* Timer_BGND_9AY_V  ------   Background  */
  {
    {
      EB_Charging_Program_Feb_Background();
    }
  }
}
