/*****************************************************************************
   Timer_ooqlV.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 16:05:33 2023
 *****************************************************************************/

#include "EB_Charging_Program_Feb.h"
#include "EB_Charging_Program_Feb_private.h"

void Timer_ooqlV(void)
{
  /* Timer_ooqlV  ------   Foreground  */
  {
    {
      EB_Charging_Program_Feb_Foreground();
    }
  }
}
