/*****************************************************************************
   can_935__0024.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Nov  6 17:25:54 2022
 *****************************************************************************/

#ifndef __CAN_935__0024_H
#define __CAN_935__0024_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_935__0024(void);
extern void post_start_CAN_935__0024(void);

/* Receive CAN object declarations */
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_8__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_8__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_8__0006(uint32_T period);
extern void can_send_72__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_72__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_72__0006(uint32_T period);
extern void can_send_71__0009(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_71__0009(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_71__0009(uint32_T period);
extern void can_send_158__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_158__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_158__0006(uint32_T period);
extern void can_send_446__0009(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_446__0009(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_446__0009(uint32_T period);
extern void can_send_447__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_447__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_447__0006(uint32_T period);
extern void can_send_485__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_485__0006(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_485__0006(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_uds_send(uint32_T period);

#endif
