/*****************************************************************************
   hw_user.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Nov  6 17:25:54 2022
 *****************************************************************************/

#ifndef HW_USER_H
#define HW_USER_H

/*****************************************************************************
   INCLUDES
 *****************************************************************************/
/*****************************************************************************
   DEFINES (REQUIRED!)
 *****************************************************************************/
// V<version>.<issue> build <build number>
#define APPLICATION_VERSION            1                         // range 0..654
#define APPLICATION_ISSUE              0                         // range 0..255
#define APPLICATION_BUILD_NUMBER       1                         // range 0..255
#define APPLICATION_PART_NUMBER        88000711                  // Unsigned 32 bit number
#define NUM_MEMORY_BLOCKS_INCLUDED_IN_APPLICATION_CHECKSUM ( 1 )
#define MEMORY_BLOCK_START_ADDRESS_1   (0x00020100)
#define MEMORY_BLOCK_LENGTH_1          (0x9FF00)
#define MEMORY_BLOCK_START_ADDRESS_2
#define MEMORY_BLOCK_LENGTH_2
#define MEMORY_BLOCK_START_ADDRESS_3
#define MEMORY_BLOCK_LENGTH_3
#define MEMORY_BLOCK_START_ADDRESS_4
#define MEMORY_BLOCK_LENGTH_4
#define MEMORY_BLOCK_START_ADDRESS_5
#define MEMORY_BLOCK_LENGTH_5
#define MEMORY_BLOCK_START_ADDRESS_6
#define MEMORY_BLOCK_LENGTH_6
#define MEMORY_BLOCK_START_ADDRESS_7
#define MEMORY_BLOCK_LENGTH_7
#define MEMORY_BLOCK_START_ADDRESS_8
#define MEMORY_BLOCK_LENGTH_8
#define MEMORY_BLOCK_START_ADDRESS_9
#define MEMORY_BLOCK_LENGTH_9
#define MEMORY_BLOCK_START_ADDRESS_10
#define MEMORY_BLOCK_LENGTH_10
#define MEMORY_BLOCK_START_ADDRESS_11
#define MEMORY_BLOCK_LENGTH_11
#define MEMORY_BLOCK_START_ADDRESS_12
#define MEMORY_BLOCK_LENGTH_12
#endif
