/*****************************************************************************
   can_3016__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 17 16:36:42 2023
 *****************************************************************************/

#ifndef __CAN_3016__0001_H
#define __CAN_3016__0001_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_3016__0001(void);
extern void post_start_CAN_3016__0001(void);

/* Receive CAN object declarations */
extern uint8_T can_get_2144__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_2017__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2017__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2017__0002(uint32_T period);
extern void can_send_2016__0005(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2016__0005(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2016__0005(uint32_T period);
extern void can_send_2145__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2145__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2145__0001(uint32_T period);
extern void can_send_2241__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2241__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2241__0001(uint32_T period);
extern void can_send_2531__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2531__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2531__0001(uint32_T period);
extern void can_send_2532__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2532__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2532__0001(uint32_T period);
extern void can_send_2529__0004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2529__0004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2529__0004(uint32_T period);
extern void can_send_2530__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2530__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2530__0001(uint32_T period);
extern void can_send_2566__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_2566__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_2566__0001(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_uds_send(uint32_T period);

#endif
