/*****************************************************************************
   can_3017__0001.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 17 16:36:42 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_NEW_Speed_Mode.h"
#include "can_3017__0001.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_3017__0001 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S7>/raptor_can_rxmsg */
void rxFn_2552__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_2552__0001[1U][8];
uint8_T rxLen_2552__0001[1U];
uint16_T rxAge_2552__0001;
uint32_T rxID_2552__0001[1U];
uint8_T rxQHead_2552__0001 = 0;
uint8_T rxQTail_2552__0001 = 0;

/* Block: <S7>/raptor_can_rxmsg2 */
void rxFn_2554__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_2554__0001[1U][8];
uint8_T rxLen_2554__0001[1U];
uint16_T rxAge_2554__0001;
uint32_T rxID_2554__0001[1U];
uint8_T rxQHead_2554__0001 = 0;
uint8_T rxQTail_2554__0001 = 0;

/* Block: <S7>/raptor_can_rxmsg1 */
void rxFn_2553__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_2553__0001[1U][8];
uint8_T rxLen_2553__0001[1U];
uint16_T rxAge_2553__0001;
uint32_T rxID_2553__0001[1U];
uint8_T rxQHead_2553__0001 = 0;
uint8_T rxQTail_2553__0001 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_3017__0001(void)
{
}                                      // end pre_start_CAN_3017__0001

void rxFn_2552__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_2552__0001[rxQHead_2552__0001][i] = b[i];
    }

    rxLen_2552__0001[rxQHead_2552__0001] = length;
    rxID_2552__0001[rxQHead_2552__0001] = id;
    if ((rxQHead_2552__0001 == rxQTail_2552__0001) && (rxAge_2552__0001 == 0))
      rxQTail_2552__0001 = (rxQTail_2552__0001 + 1) % 1U;
    if ((rxQHead_2552__0001 == (rxQTail_2552__0001 + 1)% 1U) &&
        (rxAge_2552__0001 != 0))
      rxQTail_2552__0001 = (rxQTail_2552__0001 + 1) % 1U;
    rxQHead_2552__0001 = (rxQHead_2552__0001 + 1 ) % 1U;
    rxAge_2552__0001 = 0;
  }
}

uint8_T can_get_2552__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_2552__0001;
  if (id != NULL)
    *id = rxID_2552__0001[rxQTail_2552__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_2552__0001[rxQTail_2552__0001])
    length = rxLen_2552__0001[rxQTail_2552__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_2552__0001[rxQTail_2552__0001][i];
  if ((rxQHead_2552__0001 != (rxQTail_2552__0001 + 1)% 1U) && (rxAge_2552__0001 ==
       0))
    rxQTail_2552__0001 = (rxQTail_2552__0001 + 1) % 1U;
  else if (rxAge_2552__0001 < MAX_AGE)
    rxAge_2552__0001++;
  return length;
}

void rxFn_2554__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_2554__0001[rxQHead_2554__0001][i] = b[i];
    }

    rxLen_2554__0001[rxQHead_2554__0001] = length;
    rxID_2554__0001[rxQHead_2554__0001] = id;
    if ((rxQHead_2554__0001 == rxQTail_2554__0001) && (rxAge_2554__0001 == 0))
      rxQTail_2554__0001 = (rxQTail_2554__0001 + 1) % 1U;
    if ((rxQHead_2554__0001 == (rxQTail_2554__0001 + 1)% 1U) &&
        (rxAge_2554__0001 != 0))
      rxQTail_2554__0001 = (rxQTail_2554__0001 + 1) % 1U;
    rxQHead_2554__0001 = (rxQHead_2554__0001 + 1 ) % 1U;
    rxAge_2554__0001 = 0;
  }
}

uint8_T can_get_2554__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_2554__0001;
  if (id != NULL)
    *id = rxID_2554__0001[rxQTail_2554__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_2554__0001[rxQTail_2554__0001])
    length = rxLen_2554__0001[rxQTail_2554__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_2554__0001[rxQTail_2554__0001][i];
  if ((rxQHead_2554__0001 != (rxQTail_2554__0001 + 1)% 1U) && (rxAge_2554__0001 ==
       0))
    rxQTail_2554__0001 = (rxQTail_2554__0001 + 1) % 1U;
  else if (rxAge_2554__0001 < MAX_AGE)
    rxAge_2554__0001++;
  return length;
}

void rxFn_2553__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_2553__0001[rxQHead_2553__0001][i] = b[i];
    }

    rxLen_2553__0001[rxQHead_2553__0001] = length;
    rxID_2553__0001[rxQHead_2553__0001] = id;
    if ((rxQHead_2553__0001 == rxQTail_2553__0001) && (rxAge_2553__0001 == 0))
      rxQTail_2553__0001 = (rxQTail_2553__0001 + 1) % 1U;
    if ((rxQHead_2553__0001 == (rxQTail_2553__0001 + 1)% 1U) &&
        (rxAge_2553__0001 != 0))
      rxQTail_2553__0001 = (rxQTail_2553__0001 + 1) % 1U;
    rxQHead_2553__0001 = (rxQHead_2553__0001 + 1 ) % 1U;
    rxAge_2553__0001 = 0;
  }
}

uint8_T can_get_2553__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_2553__0001;
  if (id != NULL)
    *id = rxID_2553__0001[rxQTail_2553__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_2553__0001[rxQTail_2553__0001])
    length = rxLen_2553__0001[rxQTail_2553__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_2553__0001[rxQTail_2553__0001][i];
  if ((rxQHead_2553__0001 != (rxQTail_2553__0001 + 1)% 1U) && (rxAge_2553__0001 ==
       0))
    rxQTail_2553__0001 = (rxQTail_2553__0001 + 1) % 1U;
  else if (rxAge_2553__0001 < MAX_AGE)
    rxAge_2553__0001++;
  return length;
}

void CAN_ReceiveDispatch_3017__0001(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_2552__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_2554__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_2553__0001(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_3017__0001(void)
{
  if (started_3017__0001) {
    return;
  }

  started_3017__0001 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_3017__0001 );
}                                      // end post_start_CAN_3017__0001
