/*****************************************************************************
   can_1118__0071.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 17 17:18:37 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "can_1118__0071.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_1118__0071 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S5>/raptor_can_rxmsg */
void rxFn_655__004(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_655__004[1U][8];
uint8_T rxLen_655__004[1U];
uint16_T rxAge_655__004;
uint32_T rxID_655__004[1U];
uint8_T rxQHead_655__004 = 0;
uint8_T rxQTail_655__004 = 0;

/* Block: <S5>/raptor_can_rxmsg1 */
void rxFn_656__004(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_656__004[1U][8];
uint8_T rxLen_656__004[1U];
uint16_T rxAge_656__004;
uint32_T rxID_656__004[1U];
uint8_T rxQHead_656__004 = 0;
uint8_T rxQTail_656__004 = 0;

/* Block: <S10>/raptor_can_rxmsg2 */
void rxFn_634__0043(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_634__0043[1U][8];
uint8_T rxLen_634__0043[1U];
uint16_T rxAge_634__0043;
uint32_T rxID_634__0043[1U];
uint8_T rxQHead_634__0043 = 0;
uint8_T rxQTail_634__0043 = 0;

/* Block: <S5>/raptor_can_rxmsg2 */
void rxFn_657__004(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_657__004[1U][8];
uint8_T rxLen_657__004[1U];
uint16_T rxAge_657__004;
uint32_T rxID_657__004[1U];
uint8_T rxQHead_657__004 = 0;
uint8_T rxQTail_657__004 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_1118__0071(void)
{
}                                      // end pre_start_CAN_1118__0071

void rxFn_655__004(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_655__004[rxQHead_655__004][i] = b[i];
    }

    rxLen_655__004[rxQHead_655__004] = length;
    rxID_655__004[rxQHead_655__004] = id;
    if ((rxQHead_655__004 == rxQTail_655__004) && (rxAge_655__004 == 0))
      rxQTail_655__004 = (rxQTail_655__004 + 1) % 1U;
    if ((rxQHead_655__004 == (rxQTail_655__004 + 1)% 1U) && (rxAge_655__004 != 0))
      rxQTail_655__004 = (rxQTail_655__004 + 1) % 1U;
    rxQHead_655__004 = (rxQHead_655__004 + 1 ) % 1U;
    rxAge_655__004 = 0;
  }
}

uint8_T can_get_655__004(uint16_T *age, uint32_T* id, uint8_T* extended, uint8_T
  *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_655__004;
  if (id != NULL)
    *id = rxID_655__004[rxQTail_655__004];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_655__004[rxQTail_655__004])
    length = rxLen_655__004[rxQTail_655__004];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_655__004[rxQTail_655__004][i];
  if ((rxQHead_655__004 != (rxQTail_655__004 + 1)% 1U) && (rxAge_655__004 == 0))
    rxQTail_655__004 = (rxQTail_655__004 + 1) % 1U;
  else if (rxAge_655__004 < MAX_AGE)
    rxAge_655__004++;
  return length;
}

void rxFn_656__004(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_656__004[rxQHead_656__004][i] = b[i];
    }

    rxLen_656__004[rxQHead_656__004] = length;
    rxID_656__004[rxQHead_656__004] = id;
    if ((rxQHead_656__004 == rxQTail_656__004) && (rxAge_656__004 == 0))
      rxQTail_656__004 = (rxQTail_656__004 + 1) % 1U;
    if ((rxQHead_656__004 == (rxQTail_656__004 + 1)% 1U) && (rxAge_656__004 != 0))
      rxQTail_656__004 = (rxQTail_656__004 + 1) % 1U;
    rxQHead_656__004 = (rxQHead_656__004 + 1 ) % 1U;
    rxAge_656__004 = 0;
  }
}

uint8_T can_get_656__004(uint16_T *age, uint32_T* id, uint8_T* extended, uint8_T
  *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_656__004;
  if (id != NULL)
    *id = rxID_656__004[rxQTail_656__004];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_656__004[rxQTail_656__004])
    length = rxLen_656__004[rxQTail_656__004];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_656__004[rxQTail_656__004][i];
  if ((rxQHead_656__004 != (rxQTail_656__004 + 1)% 1U) && (rxAge_656__004 == 0))
    rxQTail_656__004 = (rxQTail_656__004 + 1) % 1U;
  else if (rxAge_656__004 < MAX_AGE)
    rxAge_656__004++;
  return length;
}

void rxFn_634__0043(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_634__0043[rxQHead_634__0043][i] = b[i];
    }

    rxLen_634__0043[rxQHead_634__0043] = length;
    rxID_634__0043[rxQHead_634__0043] = id;
    if ((rxQHead_634__0043 == rxQTail_634__0043) && (rxAge_634__0043 == 0))
      rxQTail_634__0043 = (rxQTail_634__0043 + 1) % 1U;
    if ((rxQHead_634__0043 == (rxQTail_634__0043 + 1)% 1U) && (rxAge_634__0043
         != 0))
      rxQTail_634__0043 = (rxQTail_634__0043 + 1) % 1U;
    rxQHead_634__0043 = (rxQHead_634__0043 + 1 ) % 1U;
    rxAge_634__0043 = 0;
  }
}

uint8_T can_get_634__0043(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_634__0043;
  if (id != NULL)
    *id = rxID_634__0043[rxQTail_634__0043];
  if (extended != NULL)
    *extended = 0U;
  if (length > 8)
    length = 8;
  if (length > rxLen_634__0043[rxQTail_634__0043])
    length = rxLen_634__0043[rxQTail_634__0043];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_634__0043[rxQTail_634__0043][i];
  if ((rxQHead_634__0043 != (rxQTail_634__0043 + 1)% 1U) && (rxAge_634__0043 ==
       0))
    rxQTail_634__0043 = (rxQTail_634__0043 + 1) % 1U;
  else if (rxAge_634__0043 < MAX_AGE)
    rxAge_634__0043++;
  return length;
}

void rxFn_657__004(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_657__004[rxQHead_657__004][i] = b[i];
    }

    rxLen_657__004[rxQHead_657__004] = length;
    rxID_657__004[rxQHead_657__004] = id;
    if ((rxQHead_657__004 == rxQTail_657__004) && (rxAge_657__004 == 0))
      rxQTail_657__004 = (rxQTail_657__004 + 1) % 1U;
    if ((rxQHead_657__004 == (rxQTail_657__004 + 1)% 1U) && (rxAge_657__004 != 0))
      rxQTail_657__004 = (rxQTail_657__004 + 1) % 1U;
    rxQHead_657__004 = (rxQHead_657__004 + 1 ) % 1U;
    rxAge_657__004 = 0;
  }
}

uint8_T can_get_657__004(uint16_T *age, uint32_T* id, uint8_T* extended, uint8_T
  *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_657__004;
  if (id != NULL)
    *id = rxID_657__004[rxQTail_657__004];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_657__004[rxQTail_657__004])
    length = rxLen_657__004[rxQTail_657__004];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_657__004[rxQTail_657__004][i];
  if ((rxQHead_657__004 != (rxQTail_657__004 + 1)% 1U) && (rxAge_657__004 == 0))
    rxQTail_657__004 = (rxQTail_657__004 + 1) % 1U;
  else if (rxAge_657__004 < MAX_AGE)
    rxAge_657__004++;
  return length;
}

void CAN_ReceiveDispatch_1118__0071(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_655__004(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_656__004(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 0U) {
      if ((id & 0x7FF) == 0x726) {
        rxFn_634__0043(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_657__004(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_1118__0071(void)
{
  if (started_1118__0071) {
    return;
  }

  started_1118__0071 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_1118__0071 );
}                                      // end post_start_CAN_1118__0071
