/*****************************************************************************
   can_1117__0071.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 17 17:18:37 2023
 *****************************************************************************/

#ifndef __CAN_1117__0071_H
#define __CAN_1117__0071_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_1117__0071(void);
extern void post_start_CAN_1117__0071(void);

/* Receive CAN object declarations */
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_8__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_8__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_8__0013(uint32_T period);
extern void can_send_68__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_68__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_68__0013(uint32_T period);
extern void can_send_67__0016(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_67__0016(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_67__0016(uint32_T period);
extern void can_send_637__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_637__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_637__004(uint32_T period);
extern void can_send_638__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_638__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_638__004(uint32_T period);
extern void can_send_635__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_635__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_635__004(uint32_T period);
extern void can_send_345__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_345__0013(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_345__0013(uint32_T period);
extern void can_send_667__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_667__004(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_667__004(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_uds_send(uint32_T period);

#endif
