/*****************************************************************************
   can_2020__0012.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 17 16:47:54 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_OLD_CONTROLLER_Speed_Mode.h"
#include "can_2020__0012.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_2020__0012 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S8>/raptor_can_rxmsg */
void rxFn_1556__0012(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1556__0012[1U][8];
uint8_T rxLen_1556__0012[1U];
uint16_T rxAge_1556__0012;
uint32_T rxID_1556__0012[1U];
uint8_T rxQHead_1556__0012 = 0;
uint8_T rxQTail_1556__0012 = 0;

/* Block: <S8>/raptor_can_rxmsg2 */
void rxFn_1558__0012(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1558__0012[1U][8];
uint8_T rxLen_1558__0012[1U];
uint16_T rxAge_1558__0012;
uint32_T rxID_1558__0012[1U];
uint8_T rxQHead_1558__0012 = 0;
uint8_T rxQTail_1558__0012 = 0;

/* Block: <S8>/raptor_can_rxmsg1 */
void rxFn_1557__0012(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1557__0012[1U][8];
uint8_T rxLen_1557__0012[1U];
uint16_T rxAge_1557__0012;
uint32_T rxID_1557__0012[1U];
uint8_T rxQHead_1557__0012 = 0;
uint8_T rxQTail_1557__0012 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_2020__0012(void)
{
}                                      // end pre_start_CAN_2020__0012

void rxFn_1556__0012(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1556__0012[rxQHead_1556__0012][i] = b[i];
    }

    rxLen_1556__0012[rxQHead_1556__0012] = length;
    rxID_1556__0012[rxQHead_1556__0012] = id;
    if ((rxQHead_1556__0012 == rxQTail_1556__0012) && (rxAge_1556__0012 == 0))
      rxQTail_1556__0012 = (rxQTail_1556__0012 + 1) % 1U;
    if ((rxQHead_1556__0012 == (rxQTail_1556__0012 + 1)% 1U) &&
        (rxAge_1556__0012 != 0))
      rxQTail_1556__0012 = (rxQTail_1556__0012 + 1) % 1U;
    rxQHead_1556__0012 = (rxQHead_1556__0012 + 1 ) % 1U;
    rxAge_1556__0012 = 0;
  }
}

uint8_T can_get_1556__0012(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1556__0012;
  if (id != NULL)
    *id = rxID_1556__0012[rxQTail_1556__0012];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1556__0012[rxQTail_1556__0012])
    length = rxLen_1556__0012[rxQTail_1556__0012];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1556__0012[rxQTail_1556__0012][i];
  if ((rxQHead_1556__0012 != (rxQTail_1556__0012 + 1)% 1U) && (rxAge_1556__0012 ==
       0))
    rxQTail_1556__0012 = (rxQTail_1556__0012 + 1) % 1U;
  else if (rxAge_1556__0012 < MAX_AGE)
    rxAge_1556__0012++;
  return length;
}

void rxFn_1558__0012(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1558__0012[rxQHead_1558__0012][i] = b[i];
    }

    rxLen_1558__0012[rxQHead_1558__0012] = length;
    rxID_1558__0012[rxQHead_1558__0012] = id;
    if ((rxQHead_1558__0012 == rxQTail_1558__0012) && (rxAge_1558__0012 == 0))
      rxQTail_1558__0012 = (rxQTail_1558__0012 + 1) % 1U;
    if ((rxQHead_1558__0012 == (rxQTail_1558__0012 + 1)% 1U) &&
        (rxAge_1558__0012 != 0))
      rxQTail_1558__0012 = (rxQTail_1558__0012 + 1) % 1U;
    rxQHead_1558__0012 = (rxQHead_1558__0012 + 1 ) % 1U;
    rxAge_1558__0012 = 0;
  }
}

uint8_T can_get_1558__0012(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1558__0012;
  if (id != NULL)
    *id = rxID_1558__0012[rxQTail_1558__0012];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1558__0012[rxQTail_1558__0012])
    length = rxLen_1558__0012[rxQTail_1558__0012];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1558__0012[rxQTail_1558__0012][i];
  if ((rxQHead_1558__0012 != (rxQTail_1558__0012 + 1)% 1U) && (rxAge_1558__0012 ==
       0))
    rxQTail_1558__0012 = (rxQTail_1558__0012 + 1) % 1U;
  else if (rxAge_1558__0012 < MAX_AGE)
    rxAge_1558__0012++;
  return length;
}

void rxFn_1557__0012(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1557__0012[rxQHead_1557__0012][i] = b[i];
    }

    rxLen_1557__0012[rxQHead_1557__0012] = length;
    rxID_1557__0012[rxQHead_1557__0012] = id;
    if ((rxQHead_1557__0012 == rxQTail_1557__0012) && (rxAge_1557__0012 == 0))
      rxQTail_1557__0012 = (rxQTail_1557__0012 + 1) % 1U;
    if ((rxQHead_1557__0012 == (rxQTail_1557__0012 + 1)% 1U) &&
        (rxAge_1557__0012 != 0))
      rxQTail_1557__0012 = (rxQTail_1557__0012 + 1) % 1U;
    rxQHead_1557__0012 = (rxQHead_1557__0012 + 1 ) % 1U;
    rxAge_1557__0012 = 0;
  }
}

uint8_T can_get_1557__0012(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1557__0012;
  if (id != NULL)
    *id = rxID_1557__0012[rxQTail_1557__0012];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1557__0012[rxQTail_1557__0012])
    length = rxLen_1557__0012[rxQTail_1557__0012];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1557__0012[rxQTail_1557__0012][i];
  if ((rxQHead_1557__0012 != (rxQTail_1557__0012 + 1)% 1U) && (rxAge_1557__0012 ==
       0))
    rxQTail_1557__0012 = (rxQTail_1557__0012 + 1) % 1U;
  else if (rxAge_1557__0012 < MAX_AGE)
    rxAge_1557__0012++;
  return length;
}

void CAN_ReceiveDispatch_2020__0012(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_1556__0012(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_1558__0012(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_1557__0012(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_2020__0012(void)
{
  if (started_2020__0012) {
    return;
  }

  started_2020__0012 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_2020__0012 );
}                                      // end post_start_CAN_2020__0012
