/*****************************************************************************
   can_493__0006.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu Mar 31 21:02:14 2022
 *****************************************************************************/

#ifndef __CAN_493__0006_H
#define __CAN_493__0006_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_493__0006(void);
extern void post_start_CAN_493__0006(void);

/* Receive CAN object declarations */

/* Transmit CAN object declarations */
#endif
