/*****************************************************************************
   can_500__0015.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon May  2 19:02:32 2022
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU.h"
#include "can_500__0015.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_500__0015 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S8>/raptor_can_rxmsg */
void rxFn_46__0017(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_46__0017[1U][8];
uint8_T rxLen_46__0017[1U];
uint16_T rxAge_46__0017;
uint32_T rxID_46__0017[1U];
uint8_T rxQHead_46__0017 = 0;
uint8_T rxQTail_46__0017 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_500__0015(void)
{
}                                      // end pre_start_CAN_500__0015

void rxFn_46__0017(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_46__0017[rxQHead_46__0017][i] = b[i];
    }

    rxLen_46__0017[rxQHead_46__0017] = length;
    rxID_46__0017[rxQHead_46__0017] = id;
    if ((rxQHead_46__0017 == rxQTail_46__0017) && (rxAge_46__0017 == 0))
      rxQTail_46__0017 = (rxQTail_46__0017 + 1) % 1U;
    if ((rxQHead_46__0017 == (rxQTail_46__0017 + 1)% 1U) && (rxAge_46__0017 != 0))
      rxQTail_46__0017 = (rxQTail_46__0017 + 1) % 1U;
    rxQHead_46__0017 = (rxQHead_46__0017 + 1 ) % 1U;
    rxAge_46__0017 = 0;
  }
}

uint8_T can_get_46__0017(uint16_T *age, uint32_T* id, uint8_T* extended, uint8_T
  *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_46__0017;
  if (id != NULL)
    *id = rxID_46__0017[rxQTail_46__0017];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_46__0017[rxQTail_46__0017])
    length = rxLen_46__0017[rxQTail_46__0017];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_46__0017[rxQTail_46__0017][i];
  if ((rxQHead_46__0017 != (rxQTail_46__0017 + 1)% 1U) && (rxAge_46__0017 == 0))
    rxQTail_46__0017 = (rxQTail_46__0017 + 1) % 1U;
  else if (rxAge_46__0017 < MAX_AGE)
    rxAge_46__0017++;
  return length;
}

void CAN_ReceiveDispatch_500__0015(boolean extended, uint32_t id, uint8_t * data,
  uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_46__0017(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_500__0015(void)
{
  if (started_500__0015) {
    return;
  }

  started_500__0015 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_500__0015 );
}                                      // end post_start_CAN_500__0015
