/*****************************************************************************
   can_910__0001.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu May 26 11:24:05 2022
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU.h"
#include "can_910__0001.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_910__0001 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S9>/raptor_can_rxmsg */
void rxFn_446__0002(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_446__0002[1U][8];
uint8_T rxLen_446__0002[1U];
uint16_T rxAge_446__0002;
uint32_T rxID_446__0002[1U];
uint8_T rxQHead_446__0002 = 0;
uint8_T rxQTail_446__0002 = 0;

/* Block: <S9>/raptor_can_rxmsg2 */
void rxFn_448__0002(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_448__0002[1U][8];
uint8_T rxLen_448__0002[1U];
uint16_T rxAge_448__0002;
uint32_T rxID_448__0002[1U];
uint8_T rxQHead_448__0002 = 0;
uint8_T rxQTail_448__0002 = 0;

/* Block: <S9>/raptor_can_rxmsg1 */
void rxFn_447__0002(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_447__0002[1U][8];
uint8_T rxLen_447__0002[1U];
uint16_T rxAge_447__0002;
uint32_T rxID_447__0002[1U];
uint8_T rxQHead_447__0002 = 0;
uint8_T rxQTail_447__0002 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_910__0001(void)
{
}                                      // end pre_start_CAN_910__0001

void rxFn_446__0002(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_446__0002[rxQHead_446__0002][i] = b[i];
    }

    rxLen_446__0002[rxQHead_446__0002] = length;
    rxID_446__0002[rxQHead_446__0002] = id;
    if ((rxQHead_446__0002 == rxQTail_446__0002) && (rxAge_446__0002 == 0))
      rxQTail_446__0002 = (rxQTail_446__0002 + 1) % 1U;
    if ((rxQHead_446__0002 == (rxQTail_446__0002 + 1)% 1U) && (rxAge_446__0002
         != 0))
      rxQTail_446__0002 = (rxQTail_446__0002 + 1) % 1U;
    rxQHead_446__0002 = (rxQHead_446__0002 + 1 ) % 1U;
    rxAge_446__0002 = 0;
  }
}

uint8_T can_get_446__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_446__0002;
  if (id != NULL)
    *id = rxID_446__0002[rxQTail_446__0002];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_446__0002[rxQTail_446__0002])
    length = rxLen_446__0002[rxQTail_446__0002];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_446__0002[rxQTail_446__0002][i];
  if ((rxQHead_446__0002 != (rxQTail_446__0002 + 1)% 1U) && (rxAge_446__0002 ==
       0))
    rxQTail_446__0002 = (rxQTail_446__0002 + 1) % 1U;
  else if (rxAge_446__0002 < MAX_AGE)
    rxAge_446__0002++;
  return length;
}

void rxFn_448__0002(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_448__0002[rxQHead_448__0002][i] = b[i];
    }

    rxLen_448__0002[rxQHead_448__0002] = length;
    rxID_448__0002[rxQHead_448__0002] = id;
    if ((rxQHead_448__0002 == rxQTail_448__0002) && (rxAge_448__0002 == 0))
      rxQTail_448__0002 = (rxQTail_448__0002 + 1) % 1U;
    if ((rxQHead_448__0002 == (rxQTail_448__0002 + 1)% 1U) && (rxAge_448__0002
         != 0))
      rxQTail_448__0002 = (rxQTail_448__0002 + 1) % 1U;
    rxQHead_448__0002 = (rxQHead_448__0002 + 1 ) % 1U;
    rxAge_448__0002 = 0;
  }
}

uint8_T can_get_448__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_448__0002;
  if (id != NULL)
    *id = rxID_448__0002[rxQTail_448__0002];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_448__0002[rxQTail_448__0002])
    length = rxLen_448__0002[rxQTail_448__0002];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_448__0002[rxQTail_448__0002][i];
  if ((rxQHead_448__0002 != (rxQTail_448__0002 + 1)% 1U) && (rxAge_448__0002 ==
       0))
    rxQTail_448__0002 = (rxQTail_448__0002 + 1) % 1U;
  else if (rxAge_448__0002 < MAX_AGE)
    rxAge_448__0002++;
  return length;
}

void rxFn_447__0002(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_447__0002[rxQHead_447__0002][i] = b[i];
    }

    rxLen_447__0002[rxQHead_447__0002] = length;
    rxID_447__0002[rxQHead_447__0002] = id;
    if ((rxQHead_447__0002 == rxQTail_447__0002) && (rxAge_447__0002 == 0))
      rxQTail_447__0002 = (rxQTail_447__0002 + 1) % 1U;
    if ((rxQHead_447__0002 == (rxQTail_447__0002 + 1)% 1U) && (rxAge_447__0002
         != 0))
      rxQTail_447__0002 = (rxQTail_447__0002 + 1) % 1U;
    rxQHead_447__0002 = (rxQHead_447__0002 + 1 ) % 1U;
    rxAge_447__0002 = 0;
  }
}

uint8_T can_get_447__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_447__0002;
  if (id != NULL)
    *id = rxID_447__0002[rxQTail_447__0002];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_447__0002[rxQTail_447__0002])
    length = rxLen_447__0002[rxQTail_447__0002];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_447__0002[rxQTail_447__0002][i];
  if ((rxQHead_447__0002 != (rxQTail_447__0002 + 1)% 1U) && (rxAge_447__0002 ==
       0))
    rxQTail_447__0002 = (rxQTail_447__0002 + 1) % 1U;
  else if (rxAge_447__0002 < MAX_AGE)
    rxAge_447__0002++;
  return length;
}

void CAN_ReceiveDispatch_910__0001(boolean extended, uint32_t id, uint8_t * data,
  uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_446__0002(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_448__0002(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_447__0002(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_910__0001(void)
{
  if (started_910__0001) {
    return;
  }

  started_910__0001 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_910__0001 );
}                                      // end post_start_CAN_910__0001
