/*****************************************************************************
   can_756__0027.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon May 16 18:10:45 2022
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU.h"
#include "can_756__0027.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_756__0027 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S5>/raptor_can_rxmsg1 */
void rxFn_292__0012(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_292__0012[1U][8];
uint8_T rxLen_292__0012[1U];
uint16_T rxAge_292__0012;
uint32_T rxID_292__0012[1U];
uint8_T rxQHead_292__0012 = 0;
uint8_T rxQTail_292__0012 = 0;

/* Block: <S5>/raptor_can_rxmsg */
void rxFn_291__0012(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_291__0012[1U][8];
uint8_T rxLen_291__0012[1U];
uint16_T rxAge_291__0012;
uint32_T rxID_291__0012[1U];
uint8_T rxQHead_291__0012 = 0;
uint8_T rxQTail_291__0012 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_756__0027(void)
{
}                                      // end pre_start_CAN_756__0027

void rxFn_292__0012(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_292__0012[rxQHead_292__0012][i] = b[i];
    }

    rxLen_292__0012[rxQHead_292__0012] = length;
    rxID_292__0012[rxQHead_292__0012] = id;
    if ((rxQHead_292__0012 == rxQTail_292__0012) && (rxAge_292__0012 == 0))
      rxQTail_292__0012 = (rxQTail_292__0012 + 1) % 1U;
    if ((rxQHead_292__0012 == (rxQTail_292__0012 + 1)% 1U) && (rxAge_292__0012
         != 0))
      rxQTail_292__0012 = (rxQTail_292__0012 + 1) % 1U;
    rxQHead_292__0012 = (rxQHead_292__0012 + 1 ) % 1U;
    rxAge_292__0012 = 0;
  }
}

uint8_T can_get_292__0012(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_292__0012;
  if (id != NULL)
    *id = rxID_292__0012[rxQTail_292__0012];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_292__0012[rxQTail_292__0012])
    length = rxLen_292__0012[rxQTail_292__0012];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_292__0012[rxQTail_292__0012][i];
  if ((rxQHead_292__0012 != (rxQTail_292__0012 + 1)% 1U) && (rxAge_292__0012 ==
       0))
    rxQTail_292__0012 = (rxQTail_292__0012 + 1) % 1U;
  else if (rxAge_292__0012 < MAX_AGE)
    rxAge_292__0012++;
  return length;
}

void rxFn_291__0012(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_291__0012[rxQHead_291__0012][i] = b[i];
    }

    rxLen_291__0012[rxQHead_291__0012] = length;
    rxID_291__0012[rxQHead_291__0012] = id;
    if ((rxQHead_291__0012 == rxQTail_291__0012) && (rxAge_291__0012 == 0))
      rxQTail_291__0012 = (rxQTail_291__0012 + 1) % 1U;
    if ((rxQHead_291__0012 == (rxQTail_291__0012 + 1)% 1U) && (rxAge_291__0012
         != 0))
      rxQTail_291__0012 = (rxQTail_291__0012 + 1) % 1U;
    rxQHead_291__0012 = (rxQHead_291__0012 + 1 ) % 1U;
    rxAge_291__0012 = 0;
  }
}

uint8_T can_get_291__0012(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_291__0012;
  if (id != NULL)
    *id = rxID_291__0012[rxQTail_291__0012];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_291__0012[rxQTail_291__0012])
    length = rxLen_291__0012[rxQTail_291__0012];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_291__0012[rxQTail_291__0012][i];
  if ((rxQHead_291__0012 != (rxQTail_291__0012 + 1)% 1U) && (rxAge_291__0012 ==
       0))
    rxQTail_291__0012 = (rxQTail_291__0012 + 1) % 1U;
  else if (rxAge_291__0012 < MAX_AGE)
    rxAge_291__0012++;
  return length;
}

void CAN_ReceiveDispatch_756__0027(boolean extended, uint32_t id, uint8_t * data,
  uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_292__0012(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_291__0012(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_756__0027(void)
{
  if (started_756__0027) {
    return;
  }

  started_756__0027 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_756__0027 );
}                                      // end post_start_CAN_756__0027
