/*****************************************************************************
   lin_494__0006.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu Mar 31 21:02:14 2022
 *****************************************************************************/

/*   LIN Bus: LIN2 */
/*  Resource: LIN2 */
#ifndef _LIN_494__0006_H
#define _LIN_494__0006_H
#endif
