/*****************************************************************************
   lin_501__0015.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon May  2 19:02:32 2022
 *****************************************************************************/

/*   LIN Bus: LIN2 */
/*  Resource: LIN2 */
#ifndef _LIN_501__0015_H
#define _LIN_501__0015_H
#endif
