/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon May 16 18:10:45 2022
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "Lightning_McSeas_VCU_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
