/*****************************************************************************
   Timer_ooqlV.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu May 26 11:24:05 2022
 *****************************************************************************/

#include "Lightning_McSeas_VCU.h"
#include "Lightning_McSeas_VCU_private.h"

void Timer_ooqlV(void)
{
  /* Timer_ooqlV  ------   Foreground  */
  {
    {
      Lightning_McSeas_VCU_Foreground();
    }
  }
}
