/*****************************************************************************
   can_2554__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 10:24:03 2023
 *****************************************************************************/

#ifndef __CAN_2554__0001_H
#define __CAN_2554__0001_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_2554__0001(void);
extern void post_start_CAN_2554__0001(void);

/* Receive CAN object declarations */

/* Transmit CAN object declarations */
#endif
