/*****************************************************************************
   can_1063__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Jan 27 12:39:18 2023
 *****************************************************************************/

#ifndef __CAN_1063__0001_H
#define __CAN_1063__0001_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_1063__0001(void);
extern void post_start_CAN_1063__0001(void);

/* Receive CAN object declarations */
extern uint8_T can_get_599__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_600__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_174__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_601__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_175__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_175__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_175__0002(uint32_T period);

#endif
