/*****************************************************************************
   can_3350__0001.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Feb  5 16:27:08 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "can_3350__0001.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_3350__0001 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S7>/raptor_can_rxmsg */
void rxFn_1111__0033(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1111__0033[1U][8];
uint8_T rxLen_1111__0033[1U];
uint16_T rxAge_1111__0033;
uint32_T rxID_1111__0033[1U];
uint8_T rxQHead_1111__0033 = 0;
uint8_T rxQTail_1111__0033 = 0;

/* Block: <S7>/raptor_can_rxmsg1 */
void rxFn_1112__0033(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1112__0033[1U][8];
uint8_T rxLen_1112__0033[1U];
uint16_T rxAge_1112__0033;
uint32_T rxID_1112__0033[1U];
uint8_T rxQHead_1112__0033 = 0;
uint8_T rxQTail_1112__0033 = 0;

/* Block: <S9>/raptor_can_rxmsg1 */
void rxFn_174__001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_174__001[1U][8];
uint8_T rxLen_174__001[1U];
uint16_T rxAge_174__001;
uint32_T rxID_174__001[1U];
uint8_T rxQHead_174__001 = 0;
uint8_T rxQTail_174__001 = 0;

/* Block: <S7>/raptor_can_rxmsg2 */
void rxFn_1113__0033(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_1113__0033[1U][8];
uint8_T rxLen_1113__0033[1U];
uint16_T rxAge_1113__0033;
uint32_T rxID_1113__0033[1U];
uint8_T rxQHead_1113__0033 = 0;
uint8_T rxQTail_1113__0033 = 0;

/* Transmit CAN Object Declarations */
/* <S9>/raptor_can_txmsg */
uint8_T txData_175__001[1U][8U];
uint32_T txID_175__001[1U];
uint8_T txExt_175__001[1U];
uint8_T txLen_175__001[1U];
uint8_T txQHead_175__001 = 0;
uint8_T txQTail_175__001 = 0;

/* Functions */
void pre_start_CAN_3350__0001(void)
{
}                                      // end pre_start_CAN_3350__0001

void rxFn_1111__0033(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1111__0033[rxQHead_1111__0033][i] = b[i];
    }

    rxLen_1111__0033[rxQHead_1111__0033] = length;
    rxID_1111__0033[rxQHead_1111__0033] = id;
    if ((rxQHead_1111__0033 == rxQTail_1111__0033) && (rxAge_1111__0033 == 0))
      rxQTail_1111__0033 = (rxQTail_1111__0033 + 1) % 1U;
    if ((rxQHead_1111__0033 == (rxQTail_1111__0033 + 1)% 1U) &&
        (rxAge_1111__0033 != 0))
      rxQTail_1111__0033 = (rxQTail_1111__0033 + 1) % 1U;
    rxQHead_1111__0033 = (rxQHead_1111__0033 + 1 ) % 1U;
    rxAge_1111__0033 = 0;
  }
}

uint8_T can_get_1111__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1111__0033;
  if (id != NULL)
    *id = rxID_1111__0033[rxQTail_1111__0033];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1111__0033[rxQTail_1111__0033])
    length = rxLen_1111__0033[rxQTail_1111__0033];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1111__0033[rxQTail_1111__0033][i];
  if ((rxQHead_1111__0033 != (rxQTail_1111__0033 + 1)% 1U) && (rxAge_1111__0033 ==
       0))
    rxQTail_1111__0033 = (rxQTail_1111__0033 + 1) % 1U;
  else if (rxAge_1111__0033 < MAX_AGE)
    rxAge_1111__0033++;
  return length;
}

void rxFn_1112__0033(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1112__0033[rxQHead_1112__0033][i] = b[i];
    }

    rxLen_1112__0033[rxQHead_1112__0033] = length;
    rxID_1112__0033[rxQHead_1112__0033] = id;
    if ((rxQHead_1112__0033 == rxQTail_1112__0033) && (rxAge_1112__0033 == 0))
      rxQTail_1112__0033 = (rxQTail_1112__0033 + 1) % 1U;
    if ((rxQHead_1112__0033 == (rxQTail_1112__0033 + 1)% 1U) &&
        (rxAge_1112__0033 != 0))
      rxQTail_1112__0033 = (rxQTail_1112__0033 + 1) % 1U;
    rxQHead_1112__0033 = (rxQHead_1112__0033 + 1 ) % 1U;
    rxAge_1112__0033 = 0;
  }
}

uint8_T can_get_1112__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1112__0033;
  if (id != NULL)
    *id = rxID_1112__0033[rxQTail_1112__0033];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1112__0033[rxQTail_1112__0033])
    length = rxLen_1112__0033[rxQTail_1112__0033];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1112__0033[rxQTail_1112__0033][i];
  if ((rxQHead_1112__0033 != (rxQTail_1112__0033 + 1)% 1U) && (rxAge_1112__0033 ==
       0))
    rxQTail_1112__0033 = (rxQTail_1112__0033 + 1) % 1U;
  else if (rxAge_1112__0033 < MAX_AGE)
    rxAge_1112__0033++;
  return length;
}

void rxFn_174__001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_174__001[rxQHead_174__001][i] = b[i];
    }

    rxLen_174__001[rxQHead_174__001] = length;
    rxID_174__001[rxQHead_174__001] = id;
    if ((rxQHead_174__001 == rxQTail_174__001) && (rxAge_174__001 == 0))
      rxQTail_174__001 = (rxQTail_174__001 + 1) % 1U;
    if ((rxQHead_174__001 == (rxQTail_174__001 + 1)% 1U) && (rxAge_174__001 != 0))
      rxQTail_174__001 = (rxQTail_174__001 + 1) % 1U;
    rxQHead_174__001 = (rxQHead_174__001 + 1 ) % 1U;
    rxAge_174__001 = 0;
  }
}

uint8_T can_get_174__001(uint16_T *age, uint32_T* id, uint8_T* extended, uint8_T
  *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_174__001;
  if (id != NULL)
    *id = rxID_174__001[rxQTail_174__001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_174__001[rxQTail_174__001])
    length = rxLen_174__001[rxQTail_174__001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_174__001[rxQTail_174__001][i];
  if ((rxQHead_174__001 != (rxQTail_174__001 + 1)% 1U) && (rxAge_174__001 == 0))
    rxQTail_174__001 = (rxQTail_174__001 + 1) % 1U;
  else if (rxAge_174__001 < MAX_AGE)
    rxAge_174__001++;
  return length;
}

void rxFn_1113__0033(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_1113__0033[rxQHead_1113__0033][i] = b[i];
    }

    rxLen_1113__0033[rxQHead_1113__0033] = length;
    rxID_1113__0033[rxQHead_1113__0033] = id;
    if ((rxQHead_1113__0033 == rxQTail_1113__0033) && (rxAge_1113__0033 == 0))
      rxQTail_1113__0033 = (rxQTail_1113__0033 + 1) % 1U;
    if ((rxQHead_1113__0033 == (rxQTail_1113__0033 + 1)% 1U) &&
        (rxAge_1113__0033 != 0))
      rxQTail_1113__0033 = (rxQTail_1113__0033 + 1) % 1U;
    rxQHead_1113__0033 = (rxQHead_1113__0033 + 1 ) % 1U;
    rxAge_1113__0033 = 0;
  }
}

uint8_T can_get_1113__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_1113__0033;
  if (id != NULL)
    *id = rxID_1113__0033[rxQTail_1113__0033];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_1113__0033[rxQTail_1113__0033])
    length = rxLen_1113__0033[rxQTail_1113__0033];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_1113__0033[rxQTail_1113__0033][i];
  if ((rxQHead_1113__0033 != (rxQTail_1113__0033 + 1)% 1U) && (rxAge_1113__0033 ==
       0))
    rxQTail_1113__0033 = (rxQTail_1113__0033 + 1) % 1U;
  else if (rxAge_1113__0033 < MAX_AGE)
    rxAge_1113__0033++;
  return length;
}

void can_send_175__001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_3350__0001) {
    pre_start_CAN_3350__0001();
  }

  send_can_message(CAN2, extended, id, data, length);
}

void can_update_175__001(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_175__001(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void CAN_ReceiveDispatch_3350__0001(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_1111__0033(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_1112__0033(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF50E5) {
        rxFn_174__001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_1113__0033(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_3350__0001(void)
{
  if (started_3350__0001) {
    return;
  }

  started_3350__0001 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_3350__0001 );
}                                      // end post_start_CAN_3350__0001
