/*****************************************************************************
   can_3349__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Feb  5 16:27:08 2023
 *****************************************************************************/

#ifndef __CAN_3349__0001_H
#define __CAN_3349__0001_H

/*   CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_3349__0001(void);
extern void post_start_CAN_3349__0001(void);

/* Receive CAN object declarations */
extern uint8_T can_get_173__001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_BC_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_CAN1_msgID;
extern uint8_T RxTrig_XCP_BC_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_CAN1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_CAN1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_CAN1_msgID;
extern uint8_T RxTrig_XCP_CMD_CAN1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_CAN1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_72__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_72__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_72__001(uint32_T period);
extern void can_send_71__0012(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_71__0012(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_71__0012(uint32_T period);
extern void can_send_176__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_176__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_176__001(uint32_T period);
extern void can_send_177__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_177__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_177__001(uint32_T period);
extern void can_send_285__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_285__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_285__001(uint32_T period);
extern void can_send_1085__0035(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_1085__0035(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_1085__0035(uint32_T period);
extern void can_send_1086__0033(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_1086__0033(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_1086__0033(uint32_T period);
extern void can_send_1124__0032(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_1124__0032(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_1124__0032(uint32_T period);
extern void can_send_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_Tx_XCP_CAN1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_Tx_XCP_CAN1(uint32_T period);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_uds_send(uint32_T period);

#endif
