/*****************************************************************************
   can_936__0024.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Nov  6 18:28:18 2022
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "can_936__0024.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_936__0024 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S8>/raptor_can_rxmsg */
void rxFn_472__0006(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_472__0006[1U][8];
uint8_T rxLen_472__0006[1U];
uint16_T rxAge_472__0006;
uint32_T rxID_472__0006[1U];
uint8_T rxQHead_472__0006 = 0;
uint8_T rxQTail_472__0006 = 0;

/* Block: <S8>/raptor_can_rxmsg2 */
void rxFn_474__0006(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_474__0006[1U][8];
uint8_T rxLen_474__0006[1U];
uint16_T rxAge_474__0006;
uint32_T rxID_474__0006[1U];
uint8_T rxQHead_474__0006 = 0;
uint8_T rxQTail_474__0006 = 0;

/* Block: <S8>/raptor_can_rxmsg1 */
void rxFn_473__0006(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_473__0006[1U][8];
uint8_T rxLen_473__0006[1U];
uint16_T rxAge_473__0006;
uint32_T rxID_473__0006[1U];
uint8_T rxQHead_473__0006 = 0;
uint8_T rxQTail_473__0006 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_936__0024(void)
{
}                                      // end pre_start_CAN_936__0024

void rxFn_472__0006(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_472__0006[rxQHead_472__0006][i] = b[i];
    }

    rxLen_472__0006[rxQHead_472__0006] = length;
    rxID_472__0006[rxQHead_472__0006] = id;
    if ((rxQHead_472__0006 == rxQTail_472__0006) && (rxAge_472__0006 == 0))
      rxQTail_472__0006 = (rxQTail_472__0006 + 1) % 1U;
    if ((rxQHead_472__0006 == (rxQTail_472__0006 + 1)% 1U) && (rxAge_472__0006
         != 0))
      rxQTail_472__0006 = (rxQTail_472__0006 + 1) % 1U;
    rxQHead_472__0006 = (rxQHead_472__0006 + 1 ) % 1U;
    rxAge_472__0006 = 0;
  }
}

uint8_T can_get_472__0006(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_472__0006;
  if (id != NULL)
    *id = rxID_472__0006[rxQTail_472__0006];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_472__0006[rxQTail_472__0006])
    length = rxLen_472__0006[rxQTail_472__0006];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_472__0006[rxQTail_472__0006][i];
  if ((rxQHead_472__0006 != (rxQTail_472__0006 + 1)% 1U) && (rxAge_472__0006 ==
       0))
    rxQTail_472__0006 = (rxQTail_472__0006 + 1) % 1U;
  else if (rxAge_472__0006 < MAX_AGE)
    rxAge_472__0006++;
  return length;
}

void rxFn_474__0006(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_474__0006[rxQHead_474__0006][i] = b[i];
    }

    rxLen_474__0006[rxQHead_474__0006] = length;
    rxID_474__0006[rxQHead_474__0006] = id;
    if ((rxQHead_474__0006 == rxQTail_474__0006) && (rxAge_474__0006 == 0))
      rxQTail_474__0006 = (rxQTail_474__0006 + 1) % 1U;
    if ((rxQHead_474__0006 == (rxQTail_474__0006 + 1)% 1U) && (rxAge_474__0006
         != 0))
      rxQTail_474__0006 = (rxQTail_474__0006 + 1) % 1U;
    rxQHead_474__0006 = (rxQHead_474__0006 + 1 ) % 1U;
    rxAge_474__0006 = 0;
  }
}

uint8_T can_get_474__0006(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_474__0006;
  if (id != NULL)
    *id = rxID_474__0006[rxQTail_474__0006];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_474__0006[rxQTail_474__0006])
    length = rxLen_474__0006[rxQTail_474__0006];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_474__0006[rxQTail_474__0006][i];
  if ((rxQHead_474__0006 != (rxQTail_474__0006 + 1)% 1U) && (rxAge_474__0006 ==
       0))
    rxQTail_474__0006 = (rxQTail_474__0006 + 1) % 1U;
  else if (rxAge_474__0006 < MAX_AGE)
    rxAge_474__0006++;
  return length;
}

void rxFn_473__0006(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_473__0006[rxQHead_473__0006][i] = b[i];
    }

    rxLen_473__0006[rxQHead_473__0006] = length;
    rxID_473__0006[rxQHead_473__0006] = id;
    if ((rxQHead_473__0006 == rxQTail_473__0006) && (rxAge_473__0006 == 0))
      rxQTail_473__0006 = (rxQTail_473__0006 + 1) % 1U;
    if ((rxQHead_473__0006 == (rxQTail_473__0006 + 1)% 1U) && (rxAge_473__0006
         != 0))
      rxQTail_473__0006 = (rxQTail_473__0006 + 1) % 1U;
    rxQHead_473__0006 = (rxQHead_473__0006 + 1 ) % 1U;
    rxAge_473__0006 = 0;
  }
}

uint8_T can_get_473__0006(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_473__0006;
  if (id != NULL)
    *id = rxID_473__0006[rxQTail_473__0006];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_473__0006[rxQTail_473__0006])
    length = rxLen_473__0006[rxQTail_473__0006];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_473__0006[rxQTail_473__0006][i];
  if ((rxQHead_473__0006 != (rxQTail_473__0006 + 1)% 1U) && (rxAge_473__0006 ==
       0))
    rxQTail_473__0006 = (rxQTail_473__0006 + 1) % 1U;
  else if (rxAge_473__0006 < MAX_AGE)
    rxAge_473__0006++;
  return length;
}

void CAN_ReceiveDispatch_936__0024(boolean extended, uint32_t id, uint8_t * data,
  uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_472__0006(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_474__0006(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_473__0006(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_936__0024(void)
{
  if (started_936__0024) {
    return;
  }

  started_936__0024 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_936__0024 );
}                                      // end post_start_CAN_936__0024
