/*****************************************************************************
   can_1039__0031.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 09:59:18 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "can_1039__0031.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_1039__0031 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S5>/raptor_can_rxmsg */
void rxFn_576__0005(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_576__0005[1U][8];
uint8_T rxLen_576__0005[1U];
uint16_T rxAge_576__0005;
uint32_T rxID_576__0005[1U];
uint8_T rxQHead_576__0005 = 0;
uint8_T rxQTail_576__0005 = 0;

/* Block: <S5>/raptor_can_rxmsg1 */
void rxFn_577__0005(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_577__0005[1U][8];
uint8_T rxLen_577__0005[1U];
uint16_T rxAge_577__0005;
uint32_T rxID_577__0005[1U];
uint8_T rxQHead_577__0005 = 0;
uint8_T rxQTail_577__0005 = 0;

/* Block: <S5>/raptor_can_rxmsg2 */
void rxFn_578__0005(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_578__0005[1U][8];
uint8_T rxLen_578__0005[1U];
uint16_T rxAge_578__0005;
uint32_T rxID_578__0005[1U];
uint8_T rxQHead_578__0005 = 0;
uint8_T rxQTail_578__0005 = 0;

/* Transmit CAN Object Declarations */

/* Functions */
void pre_start_CAN_1039__0031(void)
{
}                                      // end pre_start_CAN_1039__0031

void rxFn_576__0005(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_576__0005[rxQHead_576__0005][i] = b[i];
    }

    rxLen_576__0005[rxQHead_576__0005] = length;
    rxID_576__0005[rxQHead_576__0005] = id;
    if ((rxQHead_576__0005 == rxQTail_576__0005) && (rxAge_576__0005 == 0))
      rxQTail_576__0005 = (rxQTail_576__0005 + 1) % 1U;
    if ((rxQHead_576__0005 == (rxQTail_576__0005 + 1)% 1U) && (rxAge_576__0005
         != 0))
      rxQTail_576__0005 = (rxQTail_576__0005 + 1) % 1U;
    rxQHead_576__0005 = (rxQHead_576__0005 + 1 ) % 1U;
    rxAge_576__0005 = 0;
  }
}

uint8_T can_get_576__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_576__0005;
  if (id != NULL)
    *id = rxID_576__0005[rxQTail_576__0005];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_576__0005[rxQTail_576__0005])
    length = rxLen_576__0005[rxQTail_576__0005];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_576__0005[rxQTail_576__0005][i];
  if ((rxQHead_576__0005 != (rxQTail_576__0005 + 1)% 1U) && (rxAge_576__0005 ==
       0))
    rxQTail_576__0005 = (rxQTail_576__0005 + 1) % 1U;
  else if (rxAge_576__0005 < MAX_AGE)
    rxAge_576__0005++;
  return length;
}

void rxFn_577__0005(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_577__0005[rxQHead_577__0005][i] = b[i];
    }

    rxLen_577__0005[rxQHead_577__0005] = length;
    rxID_577__0005[rxQHead_577__0005] = id;
    if ((rxQHead_577__0005 == rxQTail_577__0005) && (rxAge_577__0005 == 0))
      rxQTail_577__0005 = (rxQTail_577__0005 + 1) % 1U;
    if ((rxQHead_577__0005 == (rxQTail_577__0005 + 1)% 1U) && (rxAge_577__0005
         != 0))
      rxQTail_577__0005 = (rxQTail_577__0005 + 1) % 1U;
    rxQHead_577__0005 = (rxQHead_577__0005 + 1 ) % 1U;
    rxAge_577__0005 = 0;
  }
}

uint8_T can_get_577__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_577__0005;
  if (id != NULL)
    *id = rxID_577__0005[rxQTail_577__0005];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_577__0005[rxQTail_577__0005])
    length = rxLen_577__0005[rxQTail_577__0005];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_577__0005[rxQTail_577__0005][i];
  if ((rxQHead_577__0005 != (rxQTail_577__0005 + 1)% 1U) && (rxAge_577__0005 ==
       0))
    rxQTail_577__0005 = (rxQTail_577__0005 + 1) % 1U;
  else if (rxAge_577__0005 < MAX_AGE)
    rxAge_577__0005++;
  return length;
}

void rxFn_578__0005(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_578__0005[rxQHead_578__0005][i] = b[i];
    }

    rxLen_578__0005[rxQHead_578__0005] = length;
    rxID_578__0005[rxQHead_578__0005] = id;
    if ((rxQHead_578__0005 == rxQTail_578__0005) && (rxAge_578__0005 == 0))
      rxQTail_578__0005 = (rxQTail_578__0005 + 1) % 1U;
    if ((rxQHead_578__0005 == (rxQTail_578__0005 + 1)% 1U) && (rxAge_578__0005
         != 0))
      rxQTail_578__0005 = (rxQTail_578__0005 + 1) % 1U;
    rxQHead_578__0005 = (rxQHead_578__0005 + 1 ) % 1U;
    rxAge_578__0005 = 0;
  }
}

uint8_T can_get_578__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_578__0005;
  if (id != NULL)
    *id = rxID_578__0005[rxQTail_578__0005];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_578__0005[rxQTail_578__0005])
    length = rxLen_578__0005[rxQTail_578__0005];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_578__0005[rxQTail_578__0005][i];
  if ((rxQHead_578__0005 != (rxQTail_578__0005 + 1)% 1U) && (rxAge_578__0005 ==
       0))
    rxQTail_578__0005 = (rxQTail_578__0005 + 1) % 1U;
  else if (rxAge_578__0005 < MAX_AGE)
    rxAge_578__0005++;
  return length;
}

void CAN_ReceiveDispatch_1039__0031(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_576__0005(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_577__0005(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_578__0005(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_1039__0031(void)
{
  if (started_1039__0031) {
    return;
  }

  started_1039__0031 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_1039__0031 );
}                                      // end post_start_CAN_1039__0031
