/*****************************************************************************
   can_1039__0031.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 09:59:18 2023
 *****************************************************************************/

#ifndef __CAN_1039__0031_H
#define __CAN_1039__0031_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_1039__0031(void);
extern void post_start_CAN_1039__0031(void);

/* Receive CAN object declarations */
extern uint8_T can_get_576__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_577__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_578__0005(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
#endif
