/*****************************************************************************
   can_3350__0001.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Feb  5 16:27:08 2023
 *****************************************************************************/

#ifndef __CAN_3350__0001_H
#define __CAN_3350__0001_H

/*   CAN Bus: CAN2 */
/*  Resource: CAN2 */
#include "can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_3350__0001(void);
extern void post_start_CAN_3350__0001(void);

/* Receive CAN object declarations */
extern uint8_T can_get_1111__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_1112__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_174__001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_1113__0033(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);

/* Transmit CAN object declarations */
extern void can_send_175__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_update_175__001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern uint32_T can_set_period_175__001(uint32_T period);

#endif
