/*****************************************************************************
   can_1063__0001.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Jan 27 12:39:18 2023
 *****************************************************************************/

/* CAN interface: CAN2 */
/*   HW Resource: CAN2 */
#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "can_1063__0001.h"
#include "sdk_can.h"
#include "can.h"
#define MAX_AGE                        65535

int started_1063__0001 = 0;
const uint32_T CAN_CAN2_baud_rate = 250000;
uint32_T CAN_CAN2_get_baud_rate(void)
{
  return(CAN_CAN2_baud_rate);
}

/* Message Receive data storage */
/* Block: <S7>/raptor_can_rxmsg */
void rxFn_599__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_599__0001[1U][8];
uint8_T rxLen_599__0001[1U];
uint16_T rxAge_599__0001;
uint32_T rxID_599__0001[1U];
uint8_T rxQHead_599__0001 = 0;
uint8_T rxQTail_599__0001 = 0;

/* Block: <S7>/raptor_can_rxmsg1 */
void rxFn_600__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_600__0001[1U][8];
uint8_T rxLen_600__0001[1U];
uint16_T rxAge_600__0001;
uint32_T rxID_600__0001[1U];
uint8_T rxQHead_600__0001 = 0;
uint8_T rxQTail_600__0001 = 0;

/* Block: <S9>/raptor_can_rxmsg1 */
void rxFn_174__0002(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_174__0002[1U][8];
uint8_T rxLen_174__0002[1U];
uint16_T rxAge_174__0002;
uint32_T rxID_174__0002[1U];
uint8_T rxQHead_174__0002 = 0;
uint8_T rxQTail_174__0002 = 0;

/* Block: <S7>/raptor_can_rxmsg2 */
void rxFn_601__0001(unsigned int id, uint8_T len, uint8_T* data);
uint8_T rxBuf_601__0001[1U][8];
uint8_T rxLen_601__0001[1U];
uint16_T rxAge_601__0001;
uint32_T rxID_601__0001[1U];
uint8_T rxQHead_601__0001 = 0;
uint8_T rxQTail_601__0001 = 0;

/* Transmit CAN Object Declarations */
/* <S9>/raptor_can_txmsg */
uint8_T txData_175__0002[1U][8U];
uint32_T txID_175__0002[1U];
uint8_T txExt_175__0002[1U];
uint8_T txLen_175__0002[1U];
uint8_T txQHead_175__0002 = 0;
uint8_T txQTail_175__0002 = 0;

/* Functions */
void pre_start_CAN_1063__0001(void)
{
}                                      // end pre_start_CAN_1063__0001

void rxFn_599__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_599__0001[rxQHead_599__0001][i] = b[i];
    }

    rxLen_599__0001[rxQHead_599__0001] = length;
    rxID_599__0001[rxQHead_599__0001] = id;
    if ((rxQHead_599__0001 == rxQTail_599__0001) && (rxAge_599__0001 == 0))
      rxQTail_599__0001 = (rxQTail_599__0001 + 1) % 1U;
    if ((rxQHead_599__0001 == (rxQTail_599__0001 + 1)% 1U) && (rxAge_599__0001
         != 0))
      rxQTail_599__0001 = (rxQTail_599__0001 + 1) % 1U;
    rxQHead_599__0001 = (rxQHead_599__0001 + 1 ) % 1U;
    rxAge_599__0001 = 0;
  }
}

uint8_T can_get_599__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_599__0001;
  if (id != NULL)
    *id = rxID_599__0001[rxQTail_599__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_599__0001[rxQTail_599__0001])
    length = rxLen_599__0001[rxQTail_599__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_599__0001[rxQTail_599__0001][i];
  if ((rxQHead_599__0001 != (rxQTail_599__0001 + 1)% 1U) && (rxAge_599__0001 ==
       0))
    rxQTail_599__0001 = (rxQTail_599__0001 + 1) % 1U;
  else if (rxAge_599__0001 < MAX_AGE)
    rxAge_599__0001++;
  return length;
}

void rxFn_600__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_600__0001[rxQHead_600__0001][i] = b[i];
    }

    rxLen_600__0001[rxQHead_600__0001] = length;
    rxID_600__0001[rxQHead_600__0001] = id;
    if ((rxQHead_600__0001 == rxQTail_600__0001) && (rxAge_600__0001 == 0))
      rxQTail_600__0001 = (rxQTail_600__0001 + 1) % 1U;
    if ((rxQHead_600__0001 == (rxQTail_600__0001 + 1)% 1U) && (rxAge_600__0001
         != 0))
      rxQTail_600__0001 = (rxQTail_600__0001 + 1) % 1U;
    rxQHead_600__0001 = (rxQHead_600__0001 + 1 ) % 1U;
    rxAge_600__0001 = 0;
  }
}

uint8_T can_get_600__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_600__0001;
  if (id != NULL)
    *id = rxID_600__0001[rxQTail_600__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_600__0001[rxQTail_600__0001])
    length = rxLen_600__0001[rxQTail_600__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_600__0001[rxQTail_600__0001][i];
  if ((rxQHead_600__0001 != (rxQTail_600__0001 + 1)% 1U) && (rxAge_600__0001 ==
       0))
    rxQTail_600__0001 = (rxQTail_600__0001 + 1) % 1U;
  else if (rxAge_600__0001 < MAX_AGE)
    rxAge_600__0001++;
  return length;
}

void rxFn_174__0002(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_174__0002[rxQHead_174__0002][i] = b[i];
    }

    rxLen_174__0002[rxQHead_174__0002] = length;
    rxID_174__0002[rxQHead_174__0002] = id;
    if ((rxQHead_174__0002 == rxQTail_174__0002) && (rxAge_174__0002 == 0))
      rxQTail_174__0002 = (rxQTail_174__0002 + 1) % 1U;
    if ((rxQHead_174__0002 == (rxQTail_174__0002 + 1)% 1U) && (rxAge_174__0002
         != 0))
      rxQTail_174__0002 = (rxQTail_174__0002 + 1) % 1U;
    rxQHead_174__0002 = (rxQHead_174__0002 + 1 ) % 1U;
    rxAge_174__0002 = 0;
  }
}

uint8_T can_get_174__0002(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_174__0002;
  if (id != NULL)
    *id = rxID_174__0002[rxQTail_174__0002];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_174__0002[rxQTail_174__0002])
    length = rxLen_174__0002[rxQTail_174__0002];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_174__0002[rxQTail_174__0002][i];
  if ((rxQHead_174__0002 != (rxQTail_174__0002 + 1)% 1U) && (rxAge_174__0002 ==
       0))
    rxQTail_174__0002 = (rxQTail_174__0002 + 1) % 1U;
  else if (rxAge_174__0002 < MAX_AGE)
    rxAge_174__0002++;
  return length;
}

void rxFn_601__0001(unsigned int id, uint8_T length, uint8_T* data)
{
  uint8_T i;
  uint8_T* b = data;
  if ((length == 8U) ) {
    for (i = 0; i < length; i++) {
      rxBuf_601__0001[rxQHead_601__0001][i] = b[i];
    }

    rxLen_601__0001[rxQHead_601__0001] = length;
    rxID_601__0001[rxQHead_601__0001] = id;
    if ((rxQHead_601__0001 == rxQTail_601__0001) && (rxAge_601__0001 == 0))
      rxQTail_601__0001 = (rxQTail_601__0001 + 1) % 1U;
    if ((rxQHead_601__0001 == (rxQTail_601__0001 + 1)% 1U) && (rxAge_601__0001
         != 0))
      rxQTail_601__0001 = (rxQTail_601__0001 + 1) % 1U;
    rxQHead_601__0001 = (rxQHead_601__0001 + 1 ) % 1U;
    rxAge_601__0001 = 0;
  }
}

uint8_T can_get_601__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length)
{
  uint8_T i;
  if (age != NULL)
    *age = rxAge_601__0001;
  if (id != NULL)
    *id = rxID_601__0001[rxQTail_601__0001];
  if (extended != NULL)
    *extended = 1U;
  if (length > 8)
    length = 8;
  if (length > rxLen_601__0001[rxQTail_601__0001])
    length = rxLen_601__0001[rxQTail_601__0001];
  if (data != NULL)
    for (i = 0; i < length; i++)
      data[i] = rxBuf_601__0001[rxQTail_601__0001][i];
  if ((rxQHead_601__0001 != (rxQTail_601__0001 + 1)% 1U) && (rxAge_601__0001 ==
       0))
    rxQTail_601__0001 = (rxQTail_601__0001 + 1) % 1U;
  else if (rxAge_601__0001 < MAX_AGE)
    rxAge_601__0001++;
  return length;
}

void can_send_175__0002(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
  if (!started_1063__0001) {
    pre_start_CAN_1063__0001();
  }

  send_can_message(CAN2, extended, id, data, length);
}

void can_update_175__0002(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data)
{
}

uint32_T can_set_period_175__0002(uint32_T period)
{
  if (period > 65535)
    period = 65535;
  return period;
}

void CAN_ReceiveDispatch_1063__0001(boolean extended, uint32_t id, uint8_t *
  data, uint8_t data_len)
{
  extern uint8_T app_is_in_shutdown;
  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0080) {
        rxFn_599__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0180) {
        rxFn_600__0001(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF50E5) {
        rxFn_174__0002(id, data_len, data);
      }
    }
  }

  if (!app_is_in_shutdown) {
    if (extended == 1U) {
      if ((id & 0x1FFFFFFF) == 0x18FF0280) {
        rxFn_601__0001(id, data_len, data);
      }
    }
  }
}

void post_start_CAN_1063__0001(void)
{
  if (started_1063__0001) {
    return;
  }

  started_1063__0001 = 1;
  start_CAN(CAN2, CAN_CAN2_baud_rate );
  can_register_rx_callback( CAN2, CAN_ReceiveDispatch_1063__0001 );
}                                      // end post_start_CAN_1063__0001
