/*****************************************************************************
   lin_1040__0031.h
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr  7 09:59:18 2023
 *****************************************************************************/

/*   LIN Bus: LIN2 */
/*  Resource: LIN2 */
#ifndef _LIN_1040__0031_H
#define _LIN_1040__0031_H
#endif
