/*****************************************************************************
   Timer_BGND_9AY_V.c
   Generated By:
   Raptor 2021b_1.0.14409 (6115)
   Matlab (R2021b) 9.11

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Sun Nov  6 18:28:18 2022
 *****************************************************************************/

#include "Lightning_McSeas_VCU_Current_Mode.h"
#include "Lightning_McSeas_VCU_Current_Mode_private.h"

void Timer_BGND_9AY_V(void)
{
  /* Timer_BGND_9AY_V  ------   Background  */
  {
    {
      Lightning_McSeas_VCU_Current_Mode_Background();
    }
  }
}
